version: "3.8"
services:
  webntfy:
    container_name: webntfy
    image: ghcr.io/2boom-ua/webntfy:latest
    environment:
      - TZ=UTC
    ports:
      - 5511:5511
    volumes:
      - ./messages.db:/webntfy/messages.db
    restart: always


